name: suitmedia
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  dartz: ^0.10.1
  dio: ^5.5.0+1
  flutter_dotenv: ^5.1.0
  flutter:
    sdk: flutter
  freezed_annotation: ^2.2.0
  gap: ^3.0.1
  go_router: ^13.2.2
  google_fonts: ^6.2.1
  json_annotation: ^4.9.0
  provider: ^6.1.2
  flutter_svg: ^2.0.5


dev_dependencies:
  build_runner: ^2.4.8
  flutter_lints: ^3.0.0
  flutter_gen_runner: ^5.4.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.7
  json_serializable: ^6.7.1

flutter_gen:
  output: lib/utils/
  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/images/
    - .env
